version: "3.8" 


services:
  api:
    build:
      context: .
      dockerfile: TaskHub.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskHubDb;User=sa;Password=Your_password123;
    networks:
      - taskhub-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - taskhub-net

volumes:
  mssqldata:

networks:
  taskhub-net:
    drive: bridge